### ISSUE TITLE
What's your least favourite part of React & related tech

### ISSUE THREAD

**Issue by brotzky** [mxstbr/ama#10]
Mine would be: 

setup, directory structure is still ambiguous, and random things that are different and not obvious the first time running into them: attributes, animations/transitions, random debugging quirks.

Also, I still find it hard to full understand when a component will render. I swear sometimes the render() method goes off 5 times in a row for no reason... 🙃

**Comment by mxstbr** [comment]
Animation is hard. I hate animating stuff in react, though [velocity-react](https://github.com/twitter-fabric/velocity-react) is reaaaaally nice and doesn't make it too hard. It sort-of saves my life with everything animation related! :+1:
