### ISSUE TITLE
What software do you use to code?

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/ama#12]
This can mean text editors, IDEs, Git clients, terminal emulators, etc.

**Comment by mxstbr** [comment]
**Terminal**
- iTerm 2
- oh-my-zsh
- Spacegray theme

<img width="906" alt="screen shot 2016-05-07 at 10 54 17" src="https://cloud.githubusercontent.com/assets/7525670/15091218/162c40e4-1442-11e6-808b-4579d9d9830d.png">

**Editor**
- Atom
- Spacegray theme
- Operator Mono font

Favorite Packages:
- [atom-ternjs](https://atom.io/packages/atom-ternjs) (autocomplete for function names, variables etc.)
- [base16-ocean-dark-spacegray](https://atom.io/packages/base16-ocean-dark-spacegray) (theme)
- [docblockr](https://atom.io/packages/docblockr) (quick JSDoc style comments)
- [linter-alex](https://atom.io/packages/linter-alex) (Linting for prose)
- [linter-write-good](https://atom.io/packages/linter-write-good) (More linting for prose)
- [open-recent](https://atom.io/packages/open-recent) (Open recent files like Sublime for menu bar)
- [sync-settings](https://atom.io/packages/sync-settings) (Sync settings to Github)
- [synced-sidebar](https://atom.io/packages/synced-sidebar) (Sync the open file to sidebar)

![Editor Screenshot](https://i.imgur.com/OQt4i8I.png)

**Other**
- Google Chrome Dev Edition day-to-day, Canary when it's not buggy (sick new DevTools stuff)
- Slack
- Discord
- SelfControl (blocks all social media-y websites)
- Wunderlist

Any more specific questions just ask away!
