### ISSUE TITLE
What music do you listen to?

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/ama#13]

**Comment by mxstbr** [comment]
Tons of different things, mostly electronic-y though. Some favorites: [chilled, relaxed](https://open.spotify.com/track/2yzsCm9n8lbpPvntMGLc33), [dubstep](https://open.spotify.com/track/2wzPSYbxGhEJzd6BSxskU3), [DnB](https://open.spotify.com/track/0YWA5u2UOZnE6W7e3abuTE) (love DnB when programming).

I also have an obsession with _very weird, very hard electronic music_. The song that kicked that off would be the best example of that: [Swoop - Etc! Etc! & Brillz](https://open.spotify.com/track/7gTYWvkNzMmn806bV6Du44). (wait for the drop)
I have an entire playlist of that sort of thing [here](https://open.spotify.com/user/1122381232/playlist/3wIsm21EUjrTyABZYHGD9k), with [Trippy's Theme](https://open.spotify.com/track/3KRDlJT6noeJUGrSoqKirA) being my current favorite! (wait for the second drop and think about the sample reminds you off. Hint: Bedroom)

A few more links:
- [My master playlist](https://open.spotify.com/user/1122381232/playlist/4TEnQattP8s92nty5iz8I3) - Both current as well as earlier favorites, mostly sorted by time. Wild mix.
- [My chilled playlist](https://open.spotify.com/user/1122381232/playlist/3rC6Agj2issPoF1kKkLSeS) - Tons of very chilled, relaxing songs.
- [My DnB playlist](https://open.spotify.com/user/1122381232/playlist/24l7olo9y8NGsBbVBL9EYe) - My handful of favorite DnB songs.
