### ISSUE TITLE
Aside from JavaScript, what other languages do you code in?

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/ama#14]
Alternatively, what other languages are you interested in?

**Comment by mxstbr** [comment]
HTML, CSS. :trollface:

I mainly code JavaScript nowadays.
I used to do a lot of C++ and Bash in school, then Java in university and have dabbled in writing Python scripts, Ruby stuff (Rails backends, like this one: https://www.pgpasc.org), very little PHP, etc.

I'm really interested in functional programming languages, and would love to learn Elm and/or Haskell, but haven't found a suitable project and time just yet!
