### ISSUE TITLE
What do you think will be the biggest changes to the web in the next 5 years?

### ISSUE THREAD

**Issue by lencioni** [mxstbr/ama#15]

**Comment by mxstbr** [comment]
There's two big things that I think will be massive within the next 5-10 years:
1. **WebVR**: Combining the openness of the web with the amazingness of VR is a recipe for success. The big questions here are a) how fast the spec is finalised and implemented in browsers and b) how fast VR will be ubiquitous. _(I think b) is a given and will happen eventually, it's simply a time issue)_
2. **Elm**: Using WebAssembly, Elm could theoretically be ran natively on the browser. Elm as a language is amazing, no runtime errors ftw. I haven't actually looked into this at all, so I can't say for sure this will eventually happen, but if it does it'll be big. Nobody would write JavaScript anymore within ~25 years. (10 days and all that)

Let me throw that question back at you, what do you thing will be the biggest changes to the web in the next 5 years?

**Comment by lencioni** [comment]
I think that we might start to see a progression of apps moving back into the browser, just like we did with desktop apps. This will be driven by things like WebAssembly, Service Worker, and hardware improvements.

**Comment by mxstbr** [comment]
Absolutely agree with that assessment, but I think that's not only already started, it's already pretty big. Might just be living inside my bubble though! :blush:

**Comment by Pfeifenjoy** [comment]
I know it is 2021 now, but what do you think about progressiv web apps?
They seem to be a promising technology :)

Also how would you answer the question with hindsight and were do you see the future now?
