### ISSUE TITLE
What is your favorite thing in Vienna?

### ISSUE THREAD

**Issue by lencioni** [mxstbr/ama#16]

**Comment by mxstbr** [comment]
**I ❤️  Vienna**. I've travelled around the world quite a bit, but I have yet to find a place I'd rather grow old and live in.

The city is beautiful, the people are exactly my type (duh), the food is great, the public transport is incredibly nice (and cheap!), the weather is almost always pleasant, you feel safe walking around in the middle of the night everywhere,…

Choosing just one thing that's my favorite is impossible, I love all of it!

**Comment by itisbugra** [comment]
I was in Vienna 2 days ago, it would be nice to meet with you. Hope for the next time :)
