### ISSUE TITLE
Do you know any traditional/folk music from Austria?

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/ama#17]
I'm a sucker for traditional folk/music from various countries, so I was wondering if you knew of any!

**Comment by mxstbr** [comment]
There's STS, who make songs like ["Fürstenfeld"](https://www.youtube.com/watch?v=FpRmP0XUVcA) and ["Großvater"](https://www.youtube.com/watch?v=G6muwrZaYGU). (They sing in a pretty strong austrian dialect of german)

Then there's Schlager, which is pop-ish german music, like the ["Nockalm Quintett"](https://www.youtube.com/watch?v=gY4N9uc3N_Y) and the more modern version ["Helene Fischer - Atemlos"](https://www.youtube.com/watch?v=haECT-SerHk).

And then there's modern traditional music, like ["Attwenger"](https://www.youtube.com/watch?v=yRtdT8SYZOY)!

Let me know what you like/dislike. :+1:
