### ISSUE TITLE
Reason for using semicolon in react-boilerplate?

### ISSUE THREAD

**Issue by joehua87** [mxstbr/ama#18]
I see that something like code below will be better (at least in git) when remove semicolon, in case of adding new line (only change 1 line in git instead of 2)

``` js
        return state
          .set('isSubmittingEdit', false)
          .set('isEdit', false)
          .set('selected', action.payload)
```

**Comment by mxstbr** [comment]
That's, I think, the first good argument I've heard in favor of not using semicolons! :+1:

I generally have stayed with them, the biggest reason being that not having them could introduce serious bugs at some edge cases, while having them doesn't hurt per se. I think the react community has largely converged around using them, while the node community has largely converged around not using them. We'll see what the future brings I guess?

**Comment by mxstbr** [comment]
(Sorry for the non-answer, it's just that there is no particular reason to it)
