### ISSUE TITLE
Would you recommend a Mac for being a developer nowadays?

### ISSUE THREAD

**Issue by fleischie** [mxstbr/ama#19]
I am under the impression, that if you don't use a Mac nowadays, you can't be a hip dev. Do you think using Mac over Linux (for example) has some real advantages?

**Comment by mxstbr** [comment]
I have a Mac over a Linux for a variety of reasons:
- I don't want to spend days tinkering with my setup, I'd much rather tinker with my web stuff
- Retina displays are awesome
- The trackpad, oh my god the trackpad. I've yet to find a trackpad that comes even close to the niceness of the Apple one
- React Native (i.e. iOS) development
- Adobe products (i.e. Photoshop and Illustrator), I don't need them often but I do from time to time
- It does all the Unix things I'd do in Linux too

_That doesn't mean Mac's are generally better. The bang-for-the-buck is definitely better with a Linux (or even Windows) machine, for example._

Does that answer the question?

**Comment by fleischie** [comment]
Yes. It does. Although I have some sort of follow-up question (but feel free to close this one ;) )

Do you think, that this focus on the product you mentioned (in opposite of setup-tinkering) is the reason for the thing I suppose is called JavaScript-fatigue?

(Because I have to admin I really enjoyed getting to know the tools necessary for a working React app. Mostly because I like to fully understand, what I'm working with. Which probably is the reason I like to use Linux that much. But just ... you know ... mentioned casually. ;) )

**Comment by mxstbr** [comment]
No, I don't think so. I love tinkering around with all the JavaScript tooling, (that's the reason `react-boilerplate` exists!) but I haven't found the same passion in tinkering with my dotfiles or something, basically.

I do customize my setup (e.g. with the recent [`hyperterm-spacegray`](https://github.com/mxstbr/hyperterm-spacegray)) though, so maybe I just have to try Linux again sometime!
