### ISSUE TITLE
What font do you use in your editor?

### ISSUE THREAD

**Issue by whmountains** [mxstbr/ama#24]
I really like the font used in the screenshot on http://styled-components.com.  What font is it?

**Comment by mxstbr** [comment]
Operator Mono by Hoefler & Co, with the Spacegray theme! ✌️

**Comment by whmountains** [comment]
Thanks!

Caleb

On December 20, 2016 at 3:30:47 PM, Max Stoiber (notifications@github.com) wrote:

Operator Mono by Hoefler & Co, with the Spacegray theme! ✌️
