### ISSUE TITLE
Learning React

### ISSUE THREAD

**Issue by dbarabashh** [mxstbr/ama#25]
Hi Max! 
I have experience in markuping but i want to learn ReactJS. But i don't know what task i'll need to do  with this library. I know how use webpack, gulp, yarn, ES5 basic.

Thanks!

**Comment by mxstbr** [comment]
> i don't know what task i'll need to do with this library.

How do you mean? Do you need some ideas for projects to build with React?

**Comment by dbarabashh** [comment]
Yes! I meant it

**Comment by mxstbr** [comment]
I wrote this blog post: http://mxstbr.blog/2017/02/creating-open-source-projects/

The same general idea applies to how I find new projects to work on!
