### ISSUE TITLE
styled-components and greenbar

### ISSUE THREAD

**Issue by leforgedroid** [mxstbr/ama#26]
Using styled-components in react, I'm trying to create a green-bar effect where every other `<li>` is not white, but silver (or whatever other color).
What would be the best way to go about this?
I have looked into this via google/bing searches, looking at the docs, etc...
Honestly, I might be staring it right in the face and not seeing it.  My javascript skills are lacking a bit in some areas.
I apologize if this is found with a simple search.

**Comment by mxstbr** [comment]
Depends a bit on how you're rendering the `li`s, but something like this:

```JSX
const Item = styled.li`
  background: ${props => props.silver ? 'silver' : 'white'}
`

class MyList extends React.Component {
  render() {
    return (
      <ul>
        {this.props.items.map((text, index) => (
          <Item key={index} silver={index % 2 === 0} />
        )}
      </ul>
    );
  }
}
```

which you then use like this:

```JSX
<MyList items={['Hello', 'World']} />
```
