### ISSUE TITLE
optimize bundle side for reactjs apps

### ISSUE THREAD

**Issue by AlaaAttya** [mxstbr/ama#27]
what are the tricks squeeze the bundle size of a reactjs app or any frontend app?

Another question, is there a package to highlight or remove dead/unused javascript functions?

**Comment by mxstbr** [comment]
My n1 tip is to use the [`source-map-explorer`](http://npm.im/source-map-explorer) package to check which files or dependencies take up a lot of space. You'll get a visualisation that looks like this:

![](https://raw.githubusercontent.com/danvk/source-map-explorer/master/screenshot.png)

----

> Another question, is there a package to highlight or remove dead/unused javascript functions?

I don't know of one, I'm afraid!

**Comment by AlaaAttya** [comment]
this module is super, thanks dude 👍

**Comment by mxstbr** [comment]
No worries, I ❤️ `source-map-explorer`!
