### ISSUE TITLE
5 things you can't live without right now 

### ISSUE THREAD

**Issue by Createdd** [mxstbr/ama#32]
Hi @mxstbr, 
I really like the idea of this AMA. 
What are your mostly used and loved things currently? :) 
Have a great weekend ;)

**Comment by mxstbr** [comment]
- My sweater 😆 (ref: #30)
- My laptop (MBP Retina 13")
- My phone (OnePlus Two)
- My headphones (ATH m50x)
- My backpack (Minaal)

I take those things everywhere!
