### ISSUE TITLE
Are you a senior javascript developer?

### ISSUE THREAD

**Issue by ghost** [mxstbr/ama#35]

**Comment by mxstbr** [comment]
Uhm, I really don't know how to answer this question. 

On one hand, yes,  I would not think twice about applying to jobs with a title of "Senior JS Developer".

On the other hand, no idea if anybody would hire me and [I still have no idea what the hell I'm doing](https://medium.com/@mxstbr/nobody-knows-what-the-fuck-they-re-doing-b62945f88b0d). Everyday I learn something new that other developers have known for longer than I've been programming it seems. 

That's also what I love about my job. I love learning new things, experimenting with new technologies, coming up with novel solutions for problems. 

So the answer is... yes and no? I hope I always continue having that feeling of learning something new every day, of being at the forefront, feeling the joy of experimenting with new things, inventing stuff. So, I guess #juniordevforlife! ✌

**Comment by sapegin** [comment]
There are always “other developers” who know something you don’t know no matter how experienced you are. There are just too many developers with different skills and too many things you could learn but no one who knows everything ;-)

**Comment by rickmed** [comment]
@mxstbr how did you know when to start applying for senior positions?

**Comment by ariamckinley** [comment]
@rickmed not trying to answer for him, but typically senior devs are people that feel confident enough to lead and educate less experienced developers. You should not only be able to write code, but understand it enough to explain it to someone else.

But of course, nobody knows everything.
