### ISSUE TITLE
What part of the frontend tooling/development workflow do you think still has a lot of potential for improvements?

### ISSUE THREAD

**Issue by vitorbal** [mxstbr/ama#38]
In your opinion, what part of the frontend tooling/development workflow still has a lot of potential for improvements? This could also include toolings for particular areas/workflows that are not built yet or that you believe no one has built right yet.

_I'll give one suggestion of my own to get the ball rolling:_
I believe the automated refactoring tools have a huge potential in the future. For example, I love [jscodeshift](https://github.com/facebook/jscodeshift) and it has opened my eyes to the possibilities of automated refactoring, cli's to help migrate libraries to a new major version, etc., but I feel like there's still a lot of untapped potential. Maybe better APIs for common transformations, a repository of library upgrade transforms that could hook into `npm update`.. what do you think?

**Comment by mxstbr** [comment]
I love love love [`prettier`](https://github.com/prettier/prettier), it's one of the most important changes in the JavaScript ecosystem that's happened in the last months. It's incredible!

I don't know which part specifically has room for improvement, as the whole community seems to be very focussed on that area at the moment, which is great! In the part two years JavaScript as a language and the tooling around it has matured a lot. I know this is a bit of a cop out answer, but I don't really have a better one right now! If I can think of anything I'll come back to this question. 😊
