### ISSUE TITLE
Is styled components a complement or alternative to Sass, Less, Bootstrap, CSS modules, etc?

### ISSUE THREAD

**Issue by chhuang** [mxstbr/ama#39]
Can they be used together or do we have to pick a side?

**Comment by mxstbr** [comment]
It's both and neither :wink:

The answer more nuanced than that. You can't use styled-components with any of these technologies, so it's an "alternative" in that sense, but it solves different issues than Sass/Less/Bootstrap, so it's not really an alternative. Does that make any sense?

**Comment by mxstbr** [comment]
Since there was no answer here I'll close this for now. Feel free to comment if you have more questions!
