### ISSUE TITLE
What is one thing about yourself that others would be shocked to know? 

### ISSUE THREAD

**Issue by toddmotto** [mxstbr/ama#4]
;)

**Comment by mxstbr** [comment]
One of the most shocking things is that I live in an apartment in the Imperial Palace in Vienna.

[This place](https://en.wikipedia.org/wiki/Hofburg_Palace):

![hofburg](https://cloud.githubusercontent.com/assets/7525670/14412037/44138d26-ff59-11e5-8ee1-e81522af09b3.jpg)

**Comment by ppiekarczyk** [comment]
Put up more photos please!

**Comment by mxstbr** [comment]
There's a bunch more [here](https://www.flickr.com/search/?text=hofburg%20palace)!

**Comment by dubstrike** [comment]
@mxstbr What does the inside look like?

**Comment by jeresig** [comment]
@mxstbr Oh yeah, photos of the inside of your place are most definitely needed! I visited the palace this past fall but I had no idea that there were people living in there?? So cool.

**Comment by mxstbr** [comment]
Ohh I totally forgot about the photos from inside, thanks for reminding me! (sorry for the potato quality, WhatsApp compression...)

**Living room**

![whatsapp image 2017-04-13 at 17 19 35](https://cloud.githubusercontent.com/assets/7525670/25011396/7e7b19da-206d-11e7-8508-9ee1e483b6f1.jpeg)

**Bed room**

![whatsapp image 2017-04-13 at 17 19 35 1](https://cloud.githubusercontent.com/assets/7525670/25011413/897aef40-206d-11e7-8f7f-5da416130082.jpeg)
 
These are a year or so old, we've added (and are still adding) more furniture over time so it's less empty. (already have a new dining table and couches)

**Comment by mxstbr** [comment]
Most people (including most Austrians!) don't know this, but essentially the Austrian state owns too many palaces and doesn't know what to do with them. You can only have so many things to store, so they rent out apartments in all the famous palaces in and around Vienna. (including Belvedere, Schönbrunn,...)

There's a waiting list to get in, and essentially my parents put themselves on the waiting list when they were 20. A few years ago, 30-40 years later, they get a call asking if they want to rent an apartment here. At that point they didn't need it anymore, so they asked me if I wanted it. That's how I ended up here as one of the youngest inhabitants. (most of my neighbours are retired folks hah)

**Comment by peterpme** [comment]
i love that story, thanks for sharing!

**Comment by ThomasBem** [comment]
That´s super cool! :)
