### ISSUE TITLE
What kind of dogs do you prefer (also specify exact weight please)?

### ISSUE THREAD

**Issue by kitze** [mxstbr/ama#40]
Just curious 🐶

**Comment by mxstbr** [comment]
0 kilos, I like cats.

**Comment by javivelasco** [comment]
That's because you don't know this 15kg beauty:

![img_2621](https://cloud.githubusercontent.com/assets/1634922/24300645/696f9720-10ad-11e7-9b2c-8a70ec3f6e78.JPG)

**Comment by javivelasco** [comment]
That's because you don't know this 15kg beauty:

![kora](https://cloud.githubusercontent.com/assets/1634922/24300694/95e66c5c-10ad-11e7-9164-94ff2b99a684.jpg)
