### ISSUE TITLE
react-router-redux sample code for react router 4 with SSR

### ISSUE THREAD

**Issue by abhijeetNmishra** [mxstbr/ama#42]

**Comment by mxstbr** [comment]
Sorry? What's the question here?

**Comment by abhijeetNmishra** [comment]
@mxstbr i thought forum is ```ask me anything``` 😄 
Question is : After React Router 4 came out, there is no complete example of its integration with redux and server side rendering. I was looking if you know about some resourceful links :)

**Comment by abhijeetNmishra** [comment]
@mxstbr I know its too much too ask, if you don't have , i will close this without any problem

**Comment by mxstbr** [comment]
Haha sorry, I don't have time to create a full example for you but I'm sure if you ask around somebody will have done it!
