### ISSUE TITLE
What's the longterm plan for react-boilerplate?

### ISSUE THREAD

**Issue by jforaker** [mxstbr/ama#44]
I use react-boilerplate for a large project at work, we love it. We're on an older version (pre jest/styled-components).

Just wondering what the future looks like for the project? Is it on going? Will it be maintained? etc..

**Comment by mxstbr** [comment]
Yep, will stay maintained for sure!

As you can see by my slow answer here, I've been pretty busy with starting a company recently so I haven't been able to dedicate as much time as I would've liked to it, but the other maintainers have started to prepare a new release, see here: https://github.com/react-boilerplate/react-boilerplate/issues/1776

As soon as I'm making some money again I can't wait to jump back into `react-boilerplate`!
