### ISSUE TITLE
How do you come up with conference talk topics?

### ISSUE THREAD

**Issue by maxboeck** [mxstbr/ama#48]
Do you have any advice on how to best pick a topic that's "interesting enough" for a conference talk? I sometimes find it hard to define if something is worth sharing, or if it's common knowledge / yesterday's news anyway.

**Comment by mxstbr** [comment]
If it interests you it's "interesting enough" for a conference talk. I've heard amazing talks about topics you'd think are super boring/yesterdays news, but the passion of the speaker makes the talk!

As long as you're passionate about it, go do it!
