### ISSUE TITLE
Recommended redux-saga tutorials

### ISSUE THREAD

**Issue by konekoya** [mxstbr/ama#50]
Hi Max,

Just found out that [you're using redux-saga](https://github.com/mxstbr/ama/issues/49) :)
I think redux-saga is a really great tool to handle asynchronous actions in Redux. But learning how to use that is quite hard... I'm just wondering if there's any tutorial that you would recommend? I've tried the official doc, it's just too difficult for me to understand.

Thanks!

**Comment by mxstbr** [comment]
I haven't learned `redux-saga` again in a while, so it's hard for me to recommend a tutorial right now.

The thing I'd recommend is understanding how ES6 generators work **and how `redux-saga` uses them**, at which point the jump to understanding how to use `redux-saga` is much smaller. I recorded a course which explains that exact thing in 15 minutes, you can find it here: https://egghead.io/courses/write-simple-asynchronous-code-with-javascript-generators

Hope that helps!
