### ISSUE TITLE
What do you think of Linux for desktop ?

### ISSUE THREAD

**Issue by alanzanattadev** [mxstbr/ama#54]
Linux is a hard choice on new laptops because MacOS and windows are way less buggy and support a wider range of softwares. Have you used Linux on your laptop ? Which distributions ? What do you think of it ?

**Comment by mxstbr** [comment]
I've answered this question before: https://github.com/mxstbr/ama/issues/19#issuecomment-234849341

Let me throw that question back at you, do you use Linux on the desktop? Which distro?

**Comment by alanzanattadev** [comment]
I've used linux for 4 years now, going from Ubuntu to Solus , having tested Fedora, ArchLinux, and many others. I love linux because I feel right at home when using it. But in this moment, I try to work on Windows because I want to learn more from Windows. I want to have the same feeling on Windows that on Linux. I have also a Mac for developing iOS apps, but even if everything is made / available on Mac, my productivity is slowed down and I don't know why, maybe the keyboard or Mission Control that I don't use enough :) Solus is a great distribution but I don't find any perfect distribution for front end development, there is always something missing from official repo and it's painful to manually update (ex: Hyper, now, or vagrant). Today, everyone is working on MacOS :/ so everything become mac only .. :/ (design tooling, and even some IDE like Deco or Nuclide that work way better on Mac)
