### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by elizabethsiegle** [mxstbr/ama#55]
1. What book are you currently reading?

2. What is something that you don't do enough of?

3. What does your typical day look like?

**Comment by mxstbr** [comment]
1. [What I know about running coffee shops](https://whatiknowaboutrunningcoffeeshops.com/) by Colin Harmon, the three time Irish Barista Champion. Super interesting insights into the financials and business side of running your own coffee shop! (something I daydream about)

2. Skiing. 😢 I get ~20-30 days per season, but I wish I could just spend the whole winter on the slopes, carving it out, chasing the powder. One day, one day... (together with the coffee shop 😜)

3. On a typical day I'll get up between 7 and 8am, make a coffee for myself and my girlfriend, then start coding/twittering until ~12pm when we cook some lunch, then more coding until ~6pm to eat dinner (usually leftovers from lunch), then more coding/twittering/youtubing until 22pm.
Now that I put it like that, that sounds pretty boring... 🤔

**Comment by sapegin** [comment]
1. Sounds very interesting! Is it a dead tree book? It’s not clear from their site.

**Comment by mxstbr** [comment]
Yep it's a dead-tree book, it's gorgeous though. 😍  Really enjoying it!
