### ISSUE TITLE
Working remotely

### ISSUE THREAD

**Issue by areiterer** [mxstbr/ama#59]
Since you work fulltime for Thinkmill as a remote developer, I'm curious how it works out for you

- Did they employ you, or do you have your own business so you work for them by contract?
- Do you choose your work items on your own behalf or is there someone telling you what to do next?

I's pretty amazing to see what you do, keep it on ;)

**Comment by mxstbr** [comment]
> Did they employ you, or do you have your own business so you work for them by contract?

You legally cannot be employed in a country other than the one you live in, so every remote worker is officially a "business owner" with some sort of business entity that invoices their "employer". (who conversely isn't really an employer, but just a client)

This has some implications for holiday/sick pay, parental leave etc. that you need to hash out in the contract, so definitely get a lawyer to draft it to make sure you have the same benefits as an employee would have.

> Do you choose your work items on your own behalf or is there someone telling you what to do next?

A mix of both :blush:

**Comment by areiterer** [comment]
That's great, I always wondered how this is handled, since there are more and more companies hiring remote workers :)

thanks for the answer!
