### ISSUE TITLE
It

### ISSUE THREAD

**Issue by kentcdodds** [mxstbr/ama#60]

**Comment by kentcdodds** [comment]
Whoops... Hit submit too soon! I was going to make this a joke and call it "Are your GitHub notifications still empty?" Referring [this](https://twitter.com/mxstbr/status/881076581598408704). But now the joke feel flat on it's face because of my thumb mistap 🙄

**Comment by mxstbr** [comment]
Hahaha nice try though, that would've been a good one!

**Comment by mxstbr** [comment]
How's life over there?

**Comment by kentcdodds** [comment]
Oh, life's going pretty great. Been great to spend more time with family recently! How about things on your end? What's it like to be full-time on open source?

**Comment by mxstbr** [comment]
That's awesome! I definitely do too little of that.

I haven't been full-time on OSS for a few months now, I'm doing the startup thing but ssshhh don't tell anybody yet! :wink:

**Comment by kentcdodds** [comment]
Cool! So you're no longer at ThinkMill?

**Comment by mxstbr** [comment]
Nope, haven't been for like 4 months, just not announced it yet :blush:
