### ISSUE TITLE
Help for server side chart generation in pdf for React application

### ISSUE THREAD

**Issue by bishwenduk029** [mxstbr/ama#62]
Hi Max,

Hope you are doing fine. Sorry to bother you with my query. But currently, i am facing a challenge of rendering charts on server side to create a pdf and send it to customer via email. The email and the kron part I was able to to figure out. But the portion of using frontend code to generate charts at server side in pdf is a bit confusing to me. Like should be I use jsdom or phantomjs(headless browser) or use server chart library for creating such charts ?

If you could suggest or point me to some sources/references on tackling such problems, it would be of great help.

Thanks & Regards,

**Comment by mxstbr** [comment]
Unfortunately I've never done that, so I don't really know how to do it. You should probably ask on StackOverflow!

**Comment by bishwenduk029** [comment]
Thanks for the prompt reply will research it a bit.

Regards,
Bishwendu.
