### ISSUE TITLE
Do your friends code? Are they active in the community?

### ISSUE THREAD

**Issue by brotzky** [mxstbr/ama#7]
I'm asking this because most of my friends don't even know what a Frontend dev actually does. It's only my work colleagues and people I've "met" through social media that code. Kind of a random question, I know.

**Comment by mxstbr** [comment]
I'm in the same boat, most of my "core"/"old" group of friends have no idea about programming. (though some of them have started developing an interest in it and/or are studying something related)

I now have a group of Austrian developers I'm very good friends with and meet regularly though, and obviously a bunch of friends all around the world! (like you :+1:)
