### ISSUE TITLE
What are your professional goals for the next 5 years? 10 years?

### ISSUE THREAD

**Issue by joerter** [mxstbr/ama#9]

**Comment by mxstbr** [comment]
That's a tough question to answer, I'll have a think about it and get back to you in a few days!

**Comment by mxstbr** [comment]
It's been a week and I still don't have a satisfactory answer, I think.

My goal a month ago was to stop freelancing and work on a single thing, originally planning to work on a product. (i.e. join a startup) In my dreams I hoped I'd earn tons of money from a startup exit a few years down the line and could then spend my days working on open source.

Now this whole new job thing happened and now I'm being paid to work on open source, something I didn't even remotely consider a possibility.

I love what I'm doing too, the mixture of community management, product management and (of course) development of an awesome project is absolutely incredible and fascinating. It's a challenge too, I've never seriously worked with Node.js and MongoDB before, and I feel like I learn something new every day. Right now I'm happy where I am and could see myself continuing to do this for the years to come.

I know this is not the answer you expected and/or deserved, but I'll revisit this question when I have a new one. Thanks so much for asking!

**Comment by joerter** [comment]
Thanks for the answer! I've experienced similar situations where I thought I knew the path I wanted to go down, but then changed things up for whatever reason. It is definitely good to have goals, but being flexible and open to changes is also very important.
